### ISSUE TITLE
Exporting telemetry to USB is not working as expected.

### ISSUE THREAD

**Issue by chetansk** [projectOpenRAP/OpenRAP#1]
Exporting telemetry to USB is not working, as the device is mounted as read-only

Severity 2

**Comment by joel-ekstep** [comment]
Syncing telemetry via USB may not be as critical a use-case. Marking as P3 for now.

**Comment by projectOpenRAP** [comment]
Commit in progress

**Comment by projectOpenRAP** [comment]
Commit done, QA pending..

**Comment by siddharthmunot** [comment]
Some issue with the latest image, need to debug again..

**Comment by joel-ekstep** [comment]
@projectOpenRAP How are we doing on this now?

**Comment by chetansk** [comment]
Hi Joel,

We have identified the issue, RCA done. Fix is being planned. Basically,
file sync is not happening.

Thanks

C

**Comment by chetansk** [comment]
Code review submitted

**Comment by chetansk** [comment]
Code committed

**Comment by RedmineQualitrix** [comment]
I am able to export the telemetry to the USB device, hence this issue is not reproducible. Kindly let me know if you need any clarification.

**Comment by chetansk** [comment]
The bug is timer dependent. If you copy a large file and yank out the USB immediately, you will not see the files copied. 

However, I have made the fix.

**Comment by RedmineQualitrix** [comment]
This issue is reproducible in the latest build. When user tries to download the file, it is keep on loading and not able to download the file. Kindly let me know if you need any more clarification..

**Comment by siddharthmunot** [comment]
@RedmineQualitrix kindly provide with the screenshot ?

**Comment by RedmineQualitrix** [comment]
![download](https://user-images.githubusercontent.com/29939605/33660640-8f4d0d16-daaa-11e7-9f52-44ad8b312970.png)

Please find the attachment above. Kindly let me know in case of any clarification.

**Comment by rishabh1403** [comment]
Tested and verified
