### ISSUE TITLE
Opened Genie, Some contents could not able to download and in Genie home page , could able to see the deleted contents from Admin Portal in Genie.

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#11]
Steps to Reproduce:
1.Logged on to CDN home page 
2.Deleted few contents 
3.Also added more contents on the portal
4.Mobile connected to the ORAP network
5.Check the added and deleted content in Genie.

Expected Result
Should be able to download the content in Genie and deleted content in openRAP should not be visible in genie
 
Actual Result
Opened Genie, Some contents could not able to download and in Genie home page , could able to see the deleted contents from Admin Portal in Genie.

**Comment by joel-ekstep** [comment]
@RedmineQualitrix Please split into relevant bugs - it looks like multiple bugs have been merged here.

**Comment by siddharthmunot** [comment]
Verified by QA team on the new build

**Comment by RedmineQualitrix** [comment]
The issue is fixed, hence closing the issue.
