### ISSUE TITLE
After Updating the contents on openRAP everytime need to turn off and on the openRAP

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#118]
1.  Plugged in the OpenRAP Device
2. Logged in to OpenRAP Portal and update the contents in the OpenRAP portal
3. In order to see the updated changes we need to unplug the CDN device and later need to plugin the CDN device.
4. Can we able to automate as we update the contents or upgrade the firmware , the device can reboot automatically.

**Comment by siddharthmunot** [comment]
@Harishs192 As mentioned you need to click "Apply Changes" button every time you upload/download any content from the Admin Portal, also the Genie app cache has to be cleared for the changes to be reflected.

**Comment by rishabh1403** [comment]
Apply button Provided
