### ISSUE TITLE
Individual Content cannot able to delete after uploading more than 7 contents

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#119]
Logged on to OpenRAP Portal
In the Portal Home page if we upload 4 contents then delete button available for each content
Suppose if we upload more than 7 contents then delete button is disabled.

Screenshot attached:

![image](https://user-images.githubusercontent.com/18700983/36190645-5ae9026c-117f-11e8-8296-dae060d46d09.png)

**Comment by siddharthmunot** [comment]
@Harishs192 This issue doesn't seem to be consistent and if this is not a priority the new OpenRAP v2.0 dashboard takes care of it. So we might not fix it for OpenRAP V1.0, until unless very essential.

**Comment by rishabh1403** [comment]
Fixed in v2
