### ISSUE TITLE
CDN : User is not able to create new user 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#131]
1. Open the CDN and login with valid credential 
2. Click on menu and click on users 
3. Fill username and password field with valid data and click on create user
4. Observe that "Error in creating user " is displayed 

Expected Result:
 Admin should able to create new user 

Actual Result:

Admin is not able to create new user

**Comment by rishabh1403** [comment]
@RedmineQualitrix what username and password did you try ? Duplicate username and password is not allowed. Hence will throw an error.

**Comment by RedmineQualitrix** [comment]
@rishabh1403 I didn't provide the same username and password.

**Comment by rishabh1403** [comment]
@RedmineQualitrix  Can not re create it on my part. Can you please provide more details.

**Comment by badalbks** [comment]
Verify and working, Please close the issue.
