### ISSUE TITLE
CDN : Internal server error message is displaying when user tries to open any content in another tab

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#132]
Steps to reproduce 

1. Open the CDN and login with valid credential 
2. Copy or open any URL in another tab 
3. Observe that 500 internal Server Error message is displayed 

Note: The same issue is also reproducible in all the page

Expected Result: Internal server error should not displayed when user tries to open any content in another tab 

Actual Result: Internal server error message is displaying when user tries to open any content in another tab

**Comment by rishabh1403** [comment]
@RedmineQualitrix We were able to recreate it but even after the fix, user will only see login page if he tries to refresh or open in new tab. This is a single page app and is intended to work without page refresh.
It makes it more secure.
