### ISSUE TITLE
CDN : Internet connectivity is not fitting to the box

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#133]
1. Open the CDN and login with valid credential 
2. Observe that internet connectivity is not fitted to the box 

Expected Result: Internet connectivity should fit to  the box

Actual Result: Internet connectivity is not fitting to the box

**Comment by rishabh1403** [comment]
@RedmineQualitrix Can you please post a screen shot explaining the issue .

**Comment by rishabh1403** [comment]
FIxed
