### ISSUE TITLE
CDN: Proper error message is not displaying

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#134]
1. Open the CDN and  login with valid credential 
2. Click on menu and click on file management 
3. Try to delete any folder 
4. Observe that proper error message is not displaying 

Expected Result : Proper error message should display 

Actual Result: Proper error message is not displaying

**Comment by rishabh1403** [comment]
@RedmineQualitrix  Can not re create it on my part. Can you please provide more details.

**Comment by badalbks** [comment]
As discuss, need to change the message.
