### ISSUE TITLE
CDN :  Instead of "home/admin/file management" ,"home/admin" is displaying in currently at section in file management page

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#135]
1. open the CDN and login with valid credential 
2. Click on Menu and click on file management 
3. Observe that instead of "home/admin/file management", "home/admin/" is displayed 

Expected Result: Instead of "home/admin/", "home/admin/file management" should display

Actual Result: Instead of "home/admin/file management" ,"home/admin" is displaying in currently at section in file management page

**Comment by rishabh1403** [comment]
@RedmineQualitrix  this is intended, they are given access to their home directory, there they can do any operation on device, it will not screw up the box

**Comment by badalbks** [comment]
As verified, Please close the issue.
