### ISSUE TITLE
CDN: Success message is not displaying when user upload nay ecar file 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#136]
1. Open and login to the CDN 
2. Click on menu - File management 
3. Select and upload any file
4. Observe that no success message is displayed when user upload some ecar file 

Expected Result: Success message should display when user upload any ecar file 

Actual Result: Success message is not displaying when user upload nay ecar file

**Comment by rishabh1403** [comment]
@RedmineQualitrix when you upload a new file or folder, you can see the changes in real time on the web app itself, just like a file browser. Do we really need a notification here ?
