### ISSUE TITLE
CDN : User is not able to upload any content from USB device to the CDN device 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#138]
1. Open and login to the OpenRap
2. Click on file management 
3. Try to upload content from USB
4. Observe that error message is displayed when user tries to upload any content from CDN device 

Expected Result: User should able to upload any content from USB device to the CDN device 

Actual Result: User is not able to upload any content from USB device to the CDN device

**Comment by rishabh1403** [comment]
@RedmineQualitrix Can not recreate it. Please provide us with more details .
