### ISSUE TITLE
CDN device is unable to detect USB Drive and clicking on USB Upload option refreshes the page.

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#14]
Steps to Reproduce:
1. Open the OpenRAP admin page.
2. Login with valid credentials.
3. Connect a USB device to CDN.
4. Observe that the device is not able to detect the USB drive and clicking on USB Upload option refreshes the page.

Expected Results:
The Device should detect the USB drive and user should be able to upload files using USB.

Actual Results:
CDN device is unable to detect USB Drive and clicking on USB Upload option refreshes the page.

**Comment by joel-ekstep** [comment]
Not very critical for immediate release. Marking as P3.

**Comment by projectOpenRAP** [comment]
Commit in progress..

**Comment by projectOpenRAP** [comment]
Commit Done.. QA pending...

**Comment by siddharthmunot** [comment]
QA verified

**Comment by RedmineQualitrix** [comment]
The issue is fixed, hence closing the issue.
