### ISSUE TITLE
CDN : User is unable to update the SSID 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#140]
1. Open and login with valid credential to openRAp
2. Click on menu and click on modify SSID 
3. Update the name 
4. Click on update button 
5. Observe that nothing is happened 

Note: Some time internal server error message is displayed 

Expected Result: User should able to Update the SSID 

Actual Result: User is unable to update the SSID

**Comment by rishabh1403** [comment]
@RedmineQualitrix  Can not re create it.. Please provide with more details..

**Comment by badalbks** [comment]
Update is working fine, but need to change the message.
