### ISSUE TITLE
HTML Code is displayed i.e <br> and contents are not alligned properly.

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#16]
Steps to Reproduce:
1. Enter the URL.
2. Enter the valid credentials and Login.
3. Click on ""MENU"".
4. Click on ""ADD LOGO"".
5. Edit the set text description in multiple language
6. Click on ""Update Captive Portal""
7. Click on the message ""Successful updation of captive portal! **Click here** to see it"
8. Observe that HTML Code is displayed i.e <br> and contents are not alligned properly.

Expected Result:
The HTML Code should not be displayed and contents should be arranged properly.

Actual Result:
HTML Code is displayed i.e <br> and contents are not alligned properly.

![html displayed](https://user-images.githubusercontent.com/29939605/32818846-b0457668-c9eb-11e7-9f6f-76c48743bc5a.PNG)

**Comment by chetansk** [comment]
Code committed

**Comment by siddharthmunot** [comment]
QA tested

**Comment by chetansk** [comment]
Closing based on previous comments
