### ISSUE TITLE
Unable to see contents on the portal via USB Upload to Cdn Device

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#161]
1.Loaded 10 contents to pendrive 
2, Connect the pendrive to CDN device
3. Logged on to CDN portal
4. Clicked on USB upload
5. Could see loading icon
6. Pop up the successful msg
7. In portal I could not see the files
8. Where as in Genie I could able to download the contents uploaded via usb

Screenshot

![img-20180309-wa0005](https://user-images.githubusercontent.com/18700983/37209445-593b6b40-23cb-11e8-9c02-f82cacd16b7f.jpg)

**Comment by siddharthmunot** [comment]
Moved to OpenRAP v2.0, where the bug is resolved
