### ISSUE TITLE
Deleted contents from pendrive and uploaded the contents via USB to CDN

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#162]
1. Logged on to CDN portal
2. Initially 10 contents loaded to pendrive
3. Later removed 6 contents from pendrive'
4. Connected the pen drive to CDN and done upload usb
5. Successful pop up msg appears
6. Could not able to see the contents in portal
7. Whereas in Genie after clearing the data and freshly installed the Genie in Genie Home page I could see the deleted contents from pendrive in Genie

**Comment by rak16** [comment]
Fixed in the new interface
