### ISSUE TITLE
APK Package parser error

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#19]
1. Connected MI device to ekstepORAP wifi
2. Downloaded the APK
3. Clicked on installed then displays error msg as package parser error .

**Comment by siddharthmunot** [comment]
Have you disabled the security check on the MI phone to allow external apks to be installed

**Comment by Harishs192** [comment]
I have enabled the unknown sources to allow external apks to be installed from security settings.

**Comment by siddharthmunot** [comment]
Harish will confirm if the bug is seen with the new image

**Comment by Harishs192** [comment]
I tried with the latest image as well we are getting an apk parser error during installation time.

**Comment by siddharthmunot** [comment]
@mathewjpallan - Apk in not getting installed with the Latest QA built which Swangjit has provided, it was working flawlessly with the previous APKs, this does not seen to be a CDN issues, do you have any idea about this one ?

**Comment by mathewjpallan** [comment]
@siddharthmunot @Harishs192 This happens when the device OS is lower than that of the minVersion in the APK

**Comment by RedmineQualitrix** [comment]
I am testing in a device of OS 5.1 and the issue is still reproducible. Kindly let me know if you need any more clarification

**Comment by rishabh1403** [comment]
Tested and verified
