### ISSUE TITLE
Bug while updating the accepted extension Global varible

### ISSUE THREAD

**Issue by chetansk** [projectOpenRAP/OpenRAP#2]
Updating extension in Global variable page is not working

**Comment by joel-ekstep** [comment]
@chetansk What are these extensions meant to do?

**Comment by chetansk** [comment]
There different file extensions like .ecar, .mpg, ,dat etc. We have feature to make this configurable..

**Comment by joel-ekstep** [comment]
@chetansk By default, .ecar, .json and .apk are supported, for now? If so, will mark this as P3. If not, will mark as P1.

**Comment by chetansk** [comment]
Hi Joel,

Yes defaults(ecar, json, apl) are working perfectly well. Customisation is
not working.. This can be P3

Thanks
C

**Comment by siddharthmunot** [comment]
Code review submitted..

**Comment by siddharthmunot** [comment]
Commit pending...

**Comment by siddharthmunot** [comment]
Verified and closed..
