### ISSUE TITLE
Error while Installing OpeRAP on RPi

### ISSUE THREAD

**Issue by rajeshkushalkar** [projectOpenRAP/OpenRAP#206]
Hi,

After executing the below mentioned command I am getting this error while installing OpenRAP on Raspberry Pi,

pi@raspberrypi:~/OpenRAP $ ./buildimage.py

2018-04-17 00:00:55,218 - ORAP - INFO - Logfile:
/home/pi/OpenRAP/build/output_raspbian_rpi_openrap/buildimage.log
2018-04-17 00:00:55,220 - ORAP - INFO - Please wait...Creating GO dev
env in /home/pi/OpenRAP/build/go/
2018-04-17 00:00:55,221 - ORAP - INFO - cmd: go get -u
github.com/golang/dep/cmd/dep
2018-04-17 00:02:40,285 - ORAP - ERROR - Error cmd: go get -u
github.com/golang/dep/cmd/dep
b'#
github.com/golang/dep/gps\nbuild/go/src/github.com/golang/
dep/gps/constraint.go:392
<http://github.com/golang/dep/gps%5Cnbuild/go/src/github.com/golang/dep/gps/constraint.go:392>
:
undefined:
sort.SliceStable\nbuild/go/src/github.com/golang/dep/gps/constraint.go:411
:
undefined:
sort.SliceStable\nbuild/go/src/github.com/golang/dep/gps/lock.go:55:
undefined:
sort.SliceIsSorted\nbuild/go/src/github.com/golang/dep/gps/lock.go:62:
undefined: sort.Slice\n'

Anyone encountered this same issue ?

**Comment by rishabh1403** [comment]
@rajeshkushalkar  try deleting the go directory in OpenRAP/build and running the buildimage.py again.

**Comment by pronoy-debnath** [comment]
@rajeshkushalkar did it worked?

**Comment by rajeshkushalkar** [comment]
@rishabh1403  I have tried deleting the go directory still getting the error given below.

pi@raspberrypi:~/OpenRAP $ ./buildimage.py 
2018-04-24 09:41:58,356 - ORAP - INFO - Logfile: /home/pi/OpenRAP/build/output_raspbian_rpi_openrap/buildimage.log
2018-04-24 09:41:58,380 - ORAP - INFO - Please wait...Creating GO dev env in /home/pi/OpenRAP/build/go/
2018-04-24 09:41:58,382 - ORAP - INFO - cmd: go get -u github.com/golang/dep/cmd/dep
2018-04-24 09:46:24,247 - ORAP - ERROR - Error cmd: go get -u github.com/golang/dep/cmd/dep
b'package github.com/golang/dep/cmd/dep\n\timports context: unrecognized import path "context"\n'
pi@raspberrypi:~/OpenRAP $

**Comment by rajeshkushalkar** [comment]
@rishabh1403  tried deleting go directory still getting the error as follows:
$ ./buildimage.py 
2018-04-24 09:46:24,247 - ORAP - ERROR - Error cmd: go get -u github.com/golang/dep/cmd/dep
b'package github.com/golang/dep/cmd/dep\n\timports context: unrecognized import path "context"\n'

**Comment by rajeshkushalkar** [comment]
successfully Installed the OpenRAP,  have to install golang from golang website, there was issue in golang version.

now what next....

**Comment by rishabh1403** [comment]
@rajeshkushalkar Glad that it worked for you. 
Now that you have OpenRap installed you can use this for content consumption using the generic platform that comes packed with the build. Can you please let me know what is the exact requirement so that I can further assist you ?

**Comment by chetansk** [comment]
Thanks for this information, need to update the documents accordingly..

Thanks
C

**Comment by rajeshkushalkar** [comment]
@rishabh1403  thank you for your assistance!!

I have successfully built OpenRap as per the instructions.Now, I would like to install it and execute it.

under build directory following directory gets generated automatically:

output_raspbian_rpi_openrap

following is the output after doing ls :

dist  opencdn

I tried exploring these directories further but, still I am unable to figure out which command to execute in order to make it work.
 
Please, assist me further.

Thanks

**Comment by rishabh1403** [comment]
@rajeshkushalkar In the dist directory there should be a firmware file ( .tgz) , you can use that to upgrade the base image with the firmware. 
To upgrade the image you can use the device management portal . Login to the portal , go to the upgrade section and upgrade the box.

**Comment by rishabh1403** [comment]
@rajeshkushalkar You have a very old version of the  build which had lot of bugs and has evolved a lot since then. Can you please share your email so that I can share a doc with complete set of instructions to build and use openrap. Thanks.

**Comment by rishabh1403** [comment]
@rajeshkushalkar closing this, please re-open if you need any more info
