### ISSUE TITLE
Default config file is not copied

### ISSUE THREAD

**Issue by chetansk** [projectOpenRAP/OpenRAP#21]
With new changes, /var/www/ekstep dir is created by API server
But the default config is not copied into  /var/www/ekstep 
(for the latest release (0.1.0-DF) this is done manually) 
This needs a fix.

Thanks
C

**Comment by chetansk** [comment]
Causing regression and is a blocker, Hence changing to P1

**Comment by siddharthmunot** [comment]
Fixed..

**Comment by siddharthmunot** [comment]
Verified and closed..
