### ISSUE TITLE
Error in openRAP firmware installation on base image 

### ISSUE THREAD

**Issue by nidhidub** [projectOpenRAP/OpenRAP#246]
facing an error in the ./buildimage.py (step 14) of building firmware on raspberry pi 3 B+
![img_20180531_151829036_ll](https://user-images.githubusercontent.com/39790534/40825463-2353b40a-6567-11e8-81c2-f280ae24d791.jpg)
![img_20180531_151847482](https://user-images.githubusercontent.com/39790534/40825464-2382bea8-6567-11e8-8f9a-d9b0ba49a8a9.jpg)

**Comment by rishabh1403** [comment]
@nidhidub Closing this as this has been resolved.
