### ISSUE TITLE
User is not able to downlaod the apk file 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#25]
Steps to reproduce:
1.Connect to the CDN network.
2 .Login as admin and create a user(e.g. Demo)
3. Login as user 
4.Go to captive portal page.
5. Fill all the fields with valid data and apk(e.g. any other apk apart from genie) as well.
6.Click on update captive portal.
7.Open the mobile browser and type google.com.
8.Try to download the apk(newly given apk).
9..User is not able to download the apk.

Refer the video 

[2017_10_09_14_04_11.zip](https://github.com/projectOpenRAP/OpenRAP/files/1505664/2017_10_09_14_04_11.zip)

**Comment by chetansk** [comment]
Hi,
The attached video just shows, genie app stopping, do not show download. Are you suggesting, after download (which works), the app do not work ?

Thanks
C

**Comment by siddharthmunot** [comment]
@mathewjpallan Kindly have a look at this as well where the App is crashing.

**Comment by RedmineQualitrix** [comment]
@chetansk Not able to download the same Apk which is uploaded by the user. Please find the attachment for better understanding and kindly let me know for any clarification. 

[mobizen_20171127_125330.zip](https://github.com/projectOpenRAP/OpenRAP/files/1529859/mobizen_20171127_125330.zip)

**Comment by chetansk** [comment]
Hi,

We have identified an issue (thanks to Rishab), due to timing issues,
bigger logo file was causing multiple failures, including the current APK
failure. Please wait for the latest release, which is planned release
tentatively on 5th Dec.

Thanks
C

**Comment by siddharthmunot** [comment]
Test with the latest firmware code is pending

**Comment by RedmineQualitrix** [comment]
This issue is fixed, hence closing the issue.
