### ISSUE TITLE
Uploading logo and APK issues

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#28]
1. Logged on to OpenRAP admin page
2. Clicked on to Customize Captive portal --> uploaded logo , Wrote the text on set Heading row and uploaded apk.
3.  No error during uploading.
4. But when I clicked on preview, I could see the heading page as I expected, but the logo was not uploaded.
5. When I clicked on APK , I could able to download the old one, not the Latest one.

**Comment by chetansk** [comment]
@Harish

Can we talk over phone ? What is your number ?

Thanks
C

**Comment by Harishs192** [comment]
Yes .

8553458588.

**Comment by RedmineQualitrix** [comment]
Now the logo is uploaded and also able to see, but the apk file is not same as I uploaded in captive portal screen.

**Comment by rishabh1403** [comment]
Tested and verified by @RedmineQualitrix
