### ISSUE TITLE
Existing apk , logo , and the text description is not visible on the Customize portal page

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#29]
1. Logged on to OpenRAP admin page
2. Clicked on to Customize Captive portal 
3.  In the customize Captive portal on the Admin Page it would be good to see the existing apk , logo and the Text heading and description, so that user / admin can easily able to identify the logo , apk and the landing page what they have uploaded.

Currently this function is not available

**Comment by siddharthmunot** [comment]
@Harishs192 There is a small preview link at the end of the page, let me know if thats not solving the purpose.

**Comment by Harishs192** [comment]
@ Siddhart , I could not able to see the preview link after uploading the APK.

Only for the logo I could see the preview after selecting the logo itself ,

Where as for the overall preview link not available

**Comment by rishabh1403** [comment]
@Harishs192 When you upload an apk and press update... once the update is complete a line of text appears near the button which contains preview link.

**Comment by Harishs192** [comment]
@rishabh1403 , In that case, its better to put by default the preview link.
Instead of for only one particular case .

The user or the portal admin can see the preview page before making the changes every-time.

**Comment by rishabh1403** [comment]
Captive Portal Changed in V2
