### ISSUE TITLE
Add a way to provide feedback to user when logo is uploading

### ISSUE THREAD

**Issue by rishabh1403** [projectOpenRAP/OpenRAP#33]
While the logo and apk is being uploaded in change captive portal page, the browser just sits idle and user has no way to know if the process got completed or failed.

**Comment by RedmineQualitrix** [comment]
This issue is still reproducible, there is not success or failed pop up when user upload logo and apk in captive portal page.

**Comment by RedmineQualitrix** [comment]
This issue is fixed because right now we can see the message of "Uploading...!! Page will refresh once the upload completes." when user tries to  upload any image and apk. Kindly let me know if you need any clarification.
