### ISSUE TITLE
Telemetry update to cloud is not happening

### ISSUE THREAD

**Issue by chetansk** [projectOpenRAP/OpenRAP#4]
Telemetry update to cloud is not happening, since the device key is not finalized. This needs a discusison with EkStep team.

**Comment by joel-ekstep** [comment]
@chetansk Can we add Mathew, Anil here?
Telemetry is critical to our first set of pilots. Marking as P1.

**Comment by projectOpenRAP** [comment]
Work in progress...

**Comment by siddharthmunot** [comment]
Pronoy and Mathew team are working onto it

**Comment by siddharthmunot** [comment]
Tested and Verified..
