### ISSUE TITLE
CDN : captive portal modification: User is able to update the logo and apk when doesn't have access for the updation

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#40]
1. Open the admin URL
2. Login with user credential(e.g. us: demo and psw: demo)
3. Click on captive portal modification 
4. Fill all the fields with valid data and click on update button 
5. Observe that with out update permission the user is able to update the contents in captive portal modification page

Expected Result: user should not be able to update the content, when user doesn't update permission in captive portal modification page

Actual Result: User is able to update the logo and apk when doesn't have access for the updation.

**Comment by siddharthmunot** [comment]
@RedmineQualitrix please provide the screenshot where it mentions that user does not have permission to change the captive portal...

**Comment by RedmineQualitrix** [comment]
Please find the attachment below, kindly let me know in case of any clarification. 

[upload.zip](https://github.com/projectOpenRAP/OpenRAP/files/1534485/upload.zip)

**Comment by siddharthmunot** [comment]
@RedmineQualitrix Got it. thanks..

**Comment by siddharthmunot** [comment]
@RedmineQualitrix Kindly try with latest firmware code (0.1.2) https://drive.google.com/a/pinut.in/file/d/12lCRubUFdshtln_U9x8drepQLfMd5Fsl/view?usp=sharing and check the issue

**Comment by rishabh1403** [comment]
Tested and verified
