### ISSUE TITLE
CDN: Super user tasks: With out access or permission of the super admin user is able to create new user

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#41]
1. Open the CDN URL
2. Login with user credential(e.g. demo and demo)
3. Now click on menu button and click on super user tasks 
4. Click on create new user and fill all the fields with valid data 
5. Click on create new user 
6. Observe that user is able to create new user when does not have access to create any user 

Expected Result : User should not able to create any new user. New user should be created by super admin only 

Actual Result: With out access or permission of super admin user is able to create new user

**Comment by siddharthmunot** [comment]
@RedmineQualitrix please provide the screenshot..

**Comment by RedmineQualitrix** [comment]
[cdn_user.zip](https://github.com/projectOpenRAP/OpenRAP/files/1534453/cdn_user.zip)
Please find the attachment for the above issue. Kindly let me know in case of any clarification.

**Comment by siddharthmunot** [comment]
@RedmineQualitrix Let me know the permissions of test user, kindly share the screenshot for the same.

**Comment by RedmineQualitrix** [comment]
The permission is already there. 

Username  is Demo and password is Demo

**Comment by siddharthmunot** [comment]
@RedmineQualitrix Kindly try with latest firmware code (0.1.2) https://drive.google.com/a/pinut.in/file/d/12lCRubUFdshtln_U9x8drepQLfMd5Fsl/view?usp=sharing and check the issue

**Comment by rishabh1403** [comment]
tested and verified
