### ISSUE TITLE
CDN: User is not able to see all the in menu options on captive portal screen

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#42]
1. Open the CDN URL and login with user credential(test and test)
2. Click on captive portal modification 
3. Click on menu 
4. Observe that instead of all the option only file upload, change global variable and change password is displayed to the user when user is in captive portal screen 

Expected Result : User should able to see all the options in captive portal screen 

Actual Result: User  is not able to see all the options in captive portal screen. 
![user](https://user-images.githubusercontent.com/29939605/33649625-9f5ba1a2-da84-11e7-8c09-c08204c8f4c2.png)

**Comment by siddharthmunot** [comment]
@RedmineQualitrix This is because user have permissions to only perform these tasks mentioned on the Menu bar and not authorised to perform any other task.. So this seem to be not a bug

**Comment by RedmineQualitrix** [comment]
@siddharthmunot In this case why other options are displayed in  home page where user doesn't have permission.

**Comment by siddharthmunot** [comment]
@RedmineQualitrix kindly share the screenshot for the same where home page is showing all the options and also share the permissions page screenshot

**Comment by RedmineQualitrix** [comment]
Please find the attachment below. Please let know in case of any clarification. 
[42.zip](https://github.com/projectOpenRAP/OpenRAP/files/1534497/42.zip)

**Comment by rishabh1403** [comment]
tested and verified
