### ISSUE TITLE
CDN: User is able to upload the zip file in to upgrade the CDN device

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#43]
1. Open the URL and login with valid credential 
2. Click on upgrade and browse one zip file instead of tgz file 
3. Observe that user can upgrade zip file

Expected Result: User should not able to upload zip file

Actual Result : User is able to upload zip file
[zip.zip](https://github.com/projectOpenRAP/OpenRAP/files/1535153/zip.zip)

**Comment by siddharthmunot** [comment]
@RedmineQualitrix Since you selected all files on the window, thats why it took .zip file as well otherwise it only takes .tgz file ONLY and with that file the upgrade was not successful.

**Comment by RedmineQualitrix** [comment]
@siddharthmunot , If it is not supported the zip file then it should throw a error message.

**Comment by rishabh1403** [comment]
After talking to @RedmineQualitrix putting this as an enhancement, and we will work on this in upcoming release
