### ISSUE TITLE
Firmware upgrade is not working appropriately 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#45]
Steps to reproduce:
1.Connect to the CDN device.
2.Upgrade the firmware.
3.Connect the device with the CDN network.
4.Observe user is not able to see the content

Expected result:
User should be able to see the content.

**Comment by siddharthmunot** [comment]
@RedmineQualitrix Its working for me, can you share more details about the issue, video or screenshot.

**Comment by rishabh1403** [comment]
Verified
