### ISSUE TITLE
Allow the ability to add more than one APK / downloadable file on the captive portal

### ISSUE THREAD

**Issue by joel-ekstep** [projectOpenRAP/OpenRAP#46]
We have situations currently in the field, where we need to be able to download more than one APK for install (For e.g., both Genie and Diksha).

Would it be possible to make the captive portal more flexible, where it allows the user to download any of the shown links there?
(As an admin, a user could add an extra line item to the captive portal page, or delete any existing item).

cc: @siddharthmunot

**Comment by joel-ekstep** [comment]
@projectOpenRAP Can this be done max by the first/second week of Jan? If so, we could take it for a field pass.

If not, do let me know when - so we can prepare accordingly.

**Comment by rishabh1403** [comment]
Verified
