### ISSUE TITLE
Default Url for The CDN for downloading an APK

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#48]
1. Plugged in the charger for CDN Device
2. Establishes a openRAP network
3. When we select then we need to type the url for http manually.
4. Is there way of redirecting the browser to the default url instead of user typing the some other url.

**Comment by joel-ekstep** [comment]
@projectOpenRAP Attempting to go to *any* url should open the landing page (captive portal).
Let's please do the necessary investigation for this.
