### ISSUE TITLE
CDN: Individual delete option is not displaying for all the contents in file upload page

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#49]
Steps to reproduce
1. Open the URL 
2. Login with valid user credential(e.g. username- test and psw- test) 
3. Observe that individual delete option is not displaying for every contents 

Expected Result: Individual delete option should display for all the contents in file upload page

Actual Result: Individual delete option is not displaying for all the contents in file upload page

OS: windows

Browser: Chrome 62
![delete](https://user-images.githubusercontent.com/29939605/34098770-78a61636-e403-11e7-91c0-80487c8be211.png)

**Comment by siddharthmunot** [comment]
The issue only happens for the non admin/root users, for root users this works fine, since this is not blocking marking it as an enhancement and will be resolved in v2.
