### ISSUE TITLE
File upload through USB is not happening

### ISSUE THREAD

**Issue by siddharthmunot** [projectOpenRAP/OpenRAP#5]
File Upload through USB is only uploading one file, somehow the loop is broken.

**Comment by joel-ekstep** [comment]
Marking this as P2. Should be ideally sorted out before Pratham deployment, as this was part of initial spec.

**Comment by projectOpenRAP** [comment]
Commit in progress

**Comment by projectOpenRAP** [comment]
Commit done... QA pending..

**Comment by siddharthmunot** [comment]
QA verified with the new built

**Comment by RedmineQualitrix** [comment]
Issue is fixed hence closing
