### ISSUE TITLE
CDN:  loader icon is keep on loading while the telemetry is already downloaded to the USB device

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#50]
1. Open the URL 
2. Login with valid admin credential 
3. Click on USB Download button 
4. Observe that the loader is keep on running while the telemetry is already downloaded to the USB device

Expected Result: The loader should stop loading once the telemetry finish download to the USBdevice 

Actual Result: The loader is keep on loading while the telemetry is already downloaded to the USB devic
![loader](https://user-images.githubusercontent.com/29939605/34099058-6198f494-e404-11e7-90e3-00319d35cd0e.png)
e 

OS: Windows: 10

Browser:  Chrome 62

**Comment by siddharthmunot** [comment]
Not a blocking issue, marking as an enhancement right now.
