### ISSUE TITLE
Telemetry Sync to cloud not working

### ISSUE THREAD

**Issue by Harishs192** [projectOpenRAP/OpenRAP#58]
1. Plugged in CDN device (0.1.2 Image version and Genie version 6.5.2608qa.33)
2. Connected Tablets to Open RAP network
3. In Tablet Installed Genie and Downloaded Contents and Clicked on Settings->Data Settings-> Clicked on Sync(Last sync showed 2/01/2018 10:17 AM)

4. I just navigate to CDN admin portal page via laptop and could able to checked for telemetry file  in the portal page
5. Later connected CDN device via USB cable and turned on USB tethering 
6. Sync doesn't happened at all.

In QA Telemtry Data could not able to find the data

**Comment by joel-ekstep** [comment]
@siddharthmunot Have we built in telemetry sync? I thought this had been completed. Please update.

**Comment by siddharthmunot** [comment]
@joel-ekstep Yes Its already there, we have see why its not working for Harish, so the plan is to again test the feature and diagnose the issue if any, will get on monday on this.@joel-ekstep Yes Its already there, we have see why its not working for Harish, so the plan is to again test the feature and diagnose the issue if any, will get on monday on this

**Comment by joel-ekstep** [comment]
@siddharthmunot The team says this hasn't been sorted out yet. Please let us know when we will be getting this?

**Comment by siddharthmunot** [comment]
@joel-ekstep @Harishs192 - @rishabh1403 Should be able to let you know the results by Thursday.
Apologies for the delay in this.

**Comment by siddharthmunot** [comment]
@joel-ekstep @Harishs192 - We have verified the issue and found the root cause of the issue as well, script is expecting internet connectivity every time and crashes if connectivity is not there, will fix it in the next release of this Version 1. If urgently required for any pilot, we can help with that as well.

**Comment by joel-ekstep** [comment]
@siddharthmunot When is the next release? Would prefer we close all items related to OpenRAP v1, so that it can be deployed as-is on field.

**Comment by Harishs192** [comment]
Hey Siddhart,

When are we expecting the new build ?

**Comment by siddharthmunot** [comment]
Done.
