### ISSUE TITLE
Unable to fetch data from OpenRAP Device

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#6]
Steps to Reproduce: 
1. Connect to CDN with device.
2. Tap on Search .
3. Enter any content name

Expected Result: 

User should be able to fetch data from CDN

Actual Result: 

Unable to fetch data from OpenRAP Device

**Comment by siddharthmunot** [comment]
Have you tried cleaning the cache of the App ?

**Comment by projectOpenRAP** [comment]
@RedmineQualitrix Have you tried Cleaning the cache of the app.

**Comment by joel-ekstep** [comment]
@projectOpenRAP This can't be an ongoing solution - can we have this fixed? It's fine for a temporary solution, but can't be there by December when it goes to Pratham.

Marking as P2.

**Comment by joel-ekstep** [comment]
@joel-ekstep Speak to Mathew about change of the cooldown period for content refresh.

**Comment by RedmineQualitrix** [comment]
As tested ,right now able to fetch the data from the CDN device.

**Comment by projectOpenRAP** [comment]
I think this has something to do "apply changes" to be clicked from the admin portal once any data is uploaded/Deleted. 
Commit in progress for the same..

**Comment by projectOpenRAP** [comment]
Commit done.. QA pending...

**Comment by siddharthmunot** [comment]
QA verified with new built

**Comment by RedmineQualitrix** [comment]
The issue is fixed, hence closing the issue.
