### ISSUE TITLE
When curropt .ecar files are uploaded the contents get hidden

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#7]
Steps To Reproduce:
1. Connect to CDN.
2. Open the login page.
3. Login with valid credentials.
4. Add a curropted .ecar files.
5. Observe that the contents get hidden.

Expected Result:
The contents should not get uploaded/ An error message should be displayed.

Actual Result:
When curropt .ecar files are uploaded the contents get hidden

Note: This is observed sometimes. i.e. out of 10 times we can say 2 times.

**Comment by joel-ekstep** [comment]
If there's corrupted ecar files, only those files should not be visible.
Marking as P2 - as it's still in closed beta currently, and doesn't require immediate fixing.

**Comment by projectOpenRAP** [comment]
Commit in progress

**Comment by projectOpenRAP** [comment]
Commit done.. QA pending...

**Comment by siddharthmunot** [comment]
QA verified with the new built

**Comment by RedmineQualitrix** [comment]
The issue is fixed, hence closing the issue.
