### ISSUE TITLE
User is able to delete files even when he doesn't have delete permission 

### ISSUE THREAD

**Issue by RedmineQualitrix** [projectOpenRAP/OpenRAP#8]
Steps To Reproduce:
1.Connect to CDN.
2.Login with valid credentials.
3.Click on user:root setting icon.
4.Go to Superusers task.
5.Create one user and do not check the delete_files checkbox.
6.Now login with this new user.
7.Observe that user still has the permission to delete files.

Expected Results:
User should not be able to delete files as he does not have the permission for deleting files.

Actual Results:
User is able to delete files.

**Comment by siddharthmunot** [comment]
Not working with the new build

**Comment by siddharthmunot** [comment]
Code review submitted..

**Comment by siddharthmunot** [comment]
Commit pending..

**Comment by rishabh1403** [comment]
Tested and verified
